Fix bug with _getNextVersionId().
digitalbazaar/bedrock-tokenization pull request #70
Opened 2021-11-03 18:39 UTC by JoshDunnDev

2021-11-03 20:17 UTC, dlongley requested changes

2021-11-03 20:17 UTC, dlongley commented on lib/batchVersions.js
> +  }
If you move this below the next conditional as an `else if`, you can remove the extra existence check on `id`.

2021-11-03 22:26 UTC, dlongley approved these changes

2021-11-04 10:31 UTC, gannan08 approved these changes

2021-11-04 16:46 UTC, merged